name = Wood
description = A layout with two row three equal height column
template = wood-layout
preview = preview.png



; ========================================
; Regions
; ========================================
regions[branding] = Branding
regions[header] = Header
regions[navigation] = Navigation
regions[highlighted] = Highlighted
regions[help] = Help
regions[footer] = Footer
regions[contactinfo] = Contact
regions[sitemap] = Site map
regions[woodcontent] = Wood Content
regions[woodleft] = Wood Left
regions[woodmiddle] = Wood Middle
regions[woodright] = Wood Right
regions[search] = Search

; ========================================
; Styles
; ========================================
stylesheets[all][] = css/layouts/wood/wood.layout.css
stylesheets[all][] = css/layouts/wood/wood.layout.no-query.css
