name = Water
description = A layout with one row
template = water-layout
preview = preview.png



; ========================================
; Regions
; ========================================
regions[branding] = Branding
regions[header] = Header
regions[navigation] = Navigation
regions[highlighted] = Highlighted
regions[help] = Help
regions[footer] = Footer
regions[contactinfo] = Contact
regions[sitemap] = Site map
regions[watercontent] = Water Content
regions[search] = Search

; ========================================
; Styles
; ========================================
stylesheets[all][] = css/layouts/water/water.layout.css
stylesheets[all][] = css/layouts/water/water.layout.no-query.css
