name = Metal
description = A layout with two rows three unequal height columns
template = metal-layout
preview = preview.png



; ========================================
; Regions
; ========================================
regions[branding] = Branding
regions[header] = Header
regions[navigation] = Navigation
regions[highlighted] = Highlighted
regions[help] = Help
regions[footer] = Footer
regions[contactinfo] = Contact
regions[sitemap] = Site map
regions[metalcontent] = Metal Content
regions[metalleft] = Metal Left
regions[metalmiddle] = Metal Middle
regions[metalright] = Metal Right
regions[search] = Search

; ========================================
; Styles
; ========================================
stylesheets[all][] = css/layouts/metal/metal.layout.css
stylesheets[all][] = css/layouts/metal/metal.layout.no-query.css
