name = Fire
description = A layout with one row three equal height columns
template = fire-layout
preview = preview.png



; ========================================
; Regions
; ========================================
regions[branding] = Branding
regions[header] = Header
regions[navigation] = Navigation
regions[highlighted] = Highlighted
regions[help] = Help
regions[footer] = Footer
regions[contactinfo] = Contact
regions[sitemap] = Site map
regions[fireleft] = Fire Left
regions[firemiddle] = Fire Middle
regions[fireright] = Fire Right
regions[search] = Search

; ========================================
; Styles
; ========================================
stylesheets[all][] = css/layouts/fire/fire.layout.css
stylesheets[all][] = css/layouts/fire/fire.layout.no-query.css
