name = Canvas
description = A layout with one row three columns
template = canvas-layout
preview = preview.png



; ========================================
; Regions
; ========================================
regions[branding] = Branding
regions[header] = Header
regions[search] = Search
regions[navigation] = Navigation
regions[highlighted] = Highlighted
regions[help] = Help
regions[footer] = Footer
regions[canvasleft] = Canvas Left
regions[canvasmiddle] = Canvas Middle
regions[canvasright] = Canvas Right
regions[contactinfo] = Contact
regions[sitemap] = Site map

; ========================================
; Styles
; ========================================
stylesheets[all][] = css/layouts/canvas/canvas.layout.css
stylesheets[all][] = css/layouts/canvas/canvas.layout.no-query.css
