name = Two row three column
description = Two row three column
template = row2col3-layout
preview = preview.png



; ========================================
; Regions
; ========================================
regions[branding] = Branding
regions[header] = Header
regions[navigation] = Navigation
regions[highlighted] = Highlighted
regions[help] = Help
regions[footer] = Footer
regions[contactinfo] = Contact
regions[sitemap] = Site map
regions[siscontent] = SIS Content
regions[sisleft] = SIS Left
regions[sismiddle] = SIS Middle
regions[sisright] = SIS Right
regions[search] = Search

; ========================================
; Styles
; ========================================
stylesheets[all][] = css/layouts/row2col3/row2col3.layout.css
stylesheets[all][] = css/layouts/row2col3/row2col3.layout.no-query.css
