name = One row three column
description = One row three column
template = row1col3-layout
preview = preview.png



; ========================================
; Regions
; ========================================
regions[branding] = Branding
regions[header] = Header
regions[search] = Search
regions[navigation] = Navigation
regions[highlighted] = Highlighted
regions[help] = Help
regions[footer] = Footer
regions[siosleft] = SIOS Left
regions[siosmiddle] = SIOS Middle
regions[siosright] = SIOS Right
regions[contactinfo] = Contact
regions[sitemap] = Site map

; ========================================
; Styles
; ========================================
stylesheets[all][] = css/layouts/row1col3/row1col3.layout.css
stylesheets[all][] = css/layouts/row1col3/row1col3.layout.no-query.css
