name = Divine
description = A layout with two row three column
template = divine-layout
preview = preview.png



; ========================================
; Regions
; ========================================
regions[branding] = Branding
regions[header] = Header
regions[navigation] = Navigation
regions[highlighted] = Highlighted
regions[help] = Help
regions[footer] = Footer
regions[contactinfo] = Contact
regions[sitemap] = Site map
regions[divinecontent] = Divine Content
regions[divineleft] = divine Left
regions[divinemiddle] = divine Middle
regions[divineright] = divine Right
regions[search] = Search

; ========================================
; Styles
; ========================================
stylesheets[all][] = css/layouts/divine/divine.layout.css
stylesheets[all][] = css/layouts/divine/divine.layout.no-query.css
